export const TRANSACTION_REPOSITORY_PORT = Symbol(
  'TRANSACTION_REPOSITORY_PORT',
);
export const PAYMENT_GATEWAY_PORT = Symbol('PAYMENT_GATEWAY_PORT');
export const CREATE_TRANSACTION_USE_CASE = Symbol(
  'CREATE_TRANSACTION_USE_CASE',
);
export const GET_TRANSACTION_USE_CASE = Symbol('GET_TRANSACTION_USE_CASE');
