export const PRODUCT_REPOSITORY_PORT = Symbol('PRODUCT_REPOSITORY_PORT');
export const GET_PRODUCTS_USE_CASE = Symbol('GET_PRODUCTS_USE_CASE');
export const GET_PRODUCT_BY_ID_USE_CASE = Symbol('GET_PRODUCT_BY_ID_USE_CASE');
